### ISSUE TITLE
Some Incompatibility with Current Metadata on 'nftshowroom.com'

### ISSUE THREAD

**Issue by Hanc1999** [Vepnar/NFTDownloader#2]
For example in function get_art_type(): 
row["image"] raises an error since no more column name "image", but summarized in a new column named "type".

Seems other columns like "cid" are also removed.

**Comment by Vepnar** [comment]
Hey Hanc1999,
They have changed their API. Because of this we are not able to access certain fields for example `year`, `royalty`, `likes` & `rights`.


It is possible to implement those fields as well as the price of the NFT's in USD & EUR.
`https://api.coingecko.com/api/v3/simple/price?ids=HIVE&vs_currencies=USD`

We can parse the year of creation & transaction information from with url:
`https://nftshowroom.com/api/arts/history`

**Comment by Vepnar** [comment]
@Hanc1999 Can you test this branch works? Could you also do a code review?

Thank you

**Comment by Vepnar** [comment]
I'll close this issue and merge the PR.
